# Generated by Django 6.1 on 2026-09-01 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='qualified_trainers', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
